export const rolesLabel= {
    ADMINISTRADOR_GENERAL: 'Administrador General',
    TAXONOMICO_GENERAL: 'Taxonómico General',
    USUARIO_GENERAL: 'Usuario General',
    ADMINISTRADOR: 'Administrador',
    DIRECTOR: 'Director',
    USUARIO: 'Usuario',
    VIVERO: 'Vivero',
    PLANTAS_VIVAS: 'Plantas Vivas',
    HERBARIO: 'Herbario',
    XILOTECA: 'Xiloteca',
    ESPERMOTECA: 'Espermoteca',
}
export const rolesArray=[
    {_id:"Administrador_General", label:"Administrador General"},
    {_id:"Taxonomico_General", label:"Taxonómico General"},
    {_id:"Usuario_General", label:"Usuario General"},
    {_id:"Administrador", label:"Administrador"},
    {_id:"Director", label:"Director"},
    {_id:"Usuario", label:"Usuario"},
    {_id:"Vivero", label:"Vivero"},
    {_id:"Plantas_Vivas", label:"Plantas Vivas"},
    {_id:"Herbario", label:"Herbario"},
    {_id:"Xiloteca", label:"Xiloteca"},
    {_id:"Espermoteca", label:"Espermoteca"},
];
export const rolesArrayOrigin=[
    "Administrador_General",
    "Taxonomico_General",
    "Usuario_General",
    "Administrador",
    "Director",
    "Usuario",
    "Vivero",
    "Plantas_Vivas",
    "Herbario",
    "Xiloteca",
    "Espermoteca",
];