/** Common*/
export const SERVER_ERROR="SERVER_ERROR";
export const LOADING_START="LOADING_START";
export const LOADING_END="LOADING_END";
export const FIRE_MSG_SNACK = "FIRE_MSG_SNACK";
export const CLOSE_MSG_SNACK = "CLOSE_MSG_SNACK";
/*Auth*/
export const LOGIN_START="LOGIN_START";
export const LOGIN_COMPLETE="LOGIN_COMPLETE";
export const LOGIN_ERROR="LOGIN_ERROR";
export const LOGIN_SERVER_ERROR="LOGIN_SERVER_ERROR";
export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_COMPLETE = "LOGOUT_COMPLETE";
export const LOAD_USER_BY_TOKEN_START="LOAD_USER_BY_TOKEN_START";
export const LOAD_USER_BY_TOKEN_COMPLETE="LOAD_USER_BY_TOKEN_COMPLETE";
export const LOAD_USER_BY_TOKEN_ERROR="LOAD_USER_BY_TOKEN_ERROR";
/* Language */
export const CHANGE_LANGUAGE_START="CHANGE_LANGUAGE_START";
export const CHANGE_LANGUAGE_COMPLETE="CHANGE_LANGUAGE_COMPLETE";
export const CHANGE_LANGUAGE_ERROR="CHANGE_LANGUAGE_ERROR";
export const LOAD_LANGUAGE_START="LOAD_LANGUAGE_START";
export const LOAD_LANGUAGE_COMPLETE="LOAD_LANGUAGE_COMPLETE";
export const LOAD_LANGUAGE_ERROR="LOAD_LANGUAGE_ERROR";
